version: "3"
services:
  api:
    build: 
      context: ./
      dockerfile: api.dockerfile
      args:
        env: local
        app_dir: /usr/src/freecar-api
    image: xanderza/freecar-api:latest
    ports:
      - "4001:3333"
      - "444:443"
    depends_on:
      - redis
    volumes:
      - /var/www/freecar-api:/usr/src/freecar-api
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6378:6379"
    volumes:
      - /home/docker/data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet: